export const ADD_ENTITY_ACTION = "ADD_ENTITY_ACTION"
export const UPDATE_ENTITY_ACTION = "UPDATE_ENTITY_ACTION"
export const DELETE_ENTITY_ACTION = "DELETE_ENTITY_ACTION"
export const SEARCH_ENTITY_ACTION = "SEARCH_ENTITY_ACTION"