export const ADD_CUSTOMER_ACTION = "ADD_CUSTOMER_ACTION"
export const UPDATE_CUSTOMER_ACTION = "UPDATE_CUSTOMER_ACTION"
export const DELETE_CUSTOMER_ACTION = "DELETE_CUSTOMER_ACTION"
export const SEARCH_CUSTOMER_ACTION = "SEARCH_CUSTOMER_ACTION"