export const ADD_EMPLOYEE_ACTION = "ADD_EMPLOYEE_ACTION"
export const UPDATE_EMPLOYEE_ACTION = "UPDATE_EMPLOYEE_ACTION"
export const DELETE_EMPLOYEE_ACTION = "DELETE_EMPLOYEE_ACTION"
export const SEARCH_EMPLOYEE_ACTION = "SEARCH_EMPLOYEE_ACTION"