export const ADD_PRODUCT_ACTION = "ADD_PRODUCT_ACTION"
export const UPDATE_PRODUCT_ACTION = "UPDATE_PRODUCT_ACTION"
export const DELETE_PRODUCT_ACTION = "DELETE_PRODUCT_ACTION"
export const SEARCH_PRODUCT_ACTION = "SEARCH_PRODUCT_ACTION"